version: '2.2'
services:

  mongo:
    container_name: unifi_mongo
    image: mongo:3.4
    networks:
      - unifi
    logging:
      driver: "json-file"
    restart: always
    volumes:
      - db:/data/db

  unifi:
    container_name: unifi
    image: "brett/unifi"
    depends_on:
      - mongo
    logging:
      driver: "json-file"
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - /var/services/homes/brett/cert_unifi:/unifi/cert
      - /var/services/homes/brett/unifi/config.gateway.json:/unifi/data/sites/default/config.gateway.json
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"

volumes:
  db:
  data:
  log:

networks:
  unifi:
